### ISSUE TITLE
TODOs after meeting Dec 22th, 2017

### ISSUE THREAD

**Issue by pachamaltese** [datachile/datachile#293]
## 1. Comuna profile

1.1. Economy
- [x] Occupations: remove most common (it's full data)
- [x] Industry by employment: remove "employment) (it's not workers)
- [x] Product space / industry space: check RC definition in cube
- [x] Employment titles (i.e by sex, by education, etc)
- [ ] Check private sector occupations
- [x] Employment by level: hardcoded order
- [ ] Income by sex + income by age: test area chart with 50% transparency
- [ ] Salaries by occupation: use boxplot and ideally violin plot
- [x] Trade balance: include numbers in tooltips

1.2. Innovation
- [x] Remove

1.3. Access to services
- [x] Reduce icons to 80%
- [ ] Check access to internet
- [x] Move long labels in health to the right
- [x] Explain Fonasa groups

1.4 Health
- [ ] Death by causes: include stack by year + growth and fractions of causes

1.4. Migration
- [x] Add stack by year (by country, colors by continent)
- [x] Check CAGR formula
- [x] Migration by visa: move to treemap
- [x] Insert descriptive titles

1.5 R+D
- [ ] Check total by business and ownership

## 2. Chile > Geo profile > Country

2.1. Education
- [ ] Remove bubble chart
- [ ] Replace by top 15 table + top school by region
- [ ] Consistent color scale in treemaps and scatterplots
- [ ] Psu results by sex: show information by test
- [ ] Consider standard deviation to build boxplots

## 3. About

- [x] Divide in pages
- [x] Include API
- [ ] Include % of contributions

## 99. Broad issues
- [ ] Check region names / comuna names (i.e Aysén vs Aisén)
- [ ] Check small comunas tht break the site (i.e Rio Ibanez, Tortel)
- [ ] Check datums that show regional data in comunas
- [x] Group continents (i.e West Africa and East Africa)
- [ ] Add next comuna and previous comuna in profiles
- [ ] Bug: click element breaks click menu
- [x] Menu: put institutions and careers in grey
- [ ] Abbreviate regions (i.e Reg Met de Santiago to Reg Meg)
- [x] Add spinner in loading banner

**Comment by cnavarreteliz** [comment]
I'll create a new issue when necessary
