### ISSUE TITLE
Issues Datachile Sprint @ Wed Dec 27, 2017 

### ISSUE THREAD

**Issue by pachamaltese** [datachile/datachile#308]
compare with https://github.com/Datawheel/datachile/issues/293 in case of duplicated todos

- [x] Add 404 page
- [x] Search R+D survey, check methodology and add note about "just private companies on this sample" or so
- [x] Fix formats on treemaps (@palamago) (i.e exports by location and # of occupations by workers, check images below)
- [x] Fix decimals vs thousands on treemaps (@palamago) (check images below)
- [x] FIx diferent NA types on visas data
- [x] Check Araucanía 2014 health access data
- [x] Country profile (@frabarz): add "source note" component (right, @palamago?) + comment about + remove "array topics"  (again, right, @palamago?)
- [x] Geo profile (@palamago): check images in sub continents or regions (i.e Africa, West)

![image 3](https://user-images.githubusercontent.com/10091065/34386628-5ba97d1e-eb08-11e7-8a5c-029ba9c5b5c7.png)
![image 2](https://user-images.githubusercontent.com/10091065/34386630-5bcd5dc4-eb08-11e7-83b5-1194fb51207f.png)
![image 1](https://user-images.githubusercontent.com/10091065/34386631-5bf0f130-eb08-11e7-92ac-c7fb71b65595.png)

**Comment by cnavarreteliz** [comment]
This was checked before Jan, 8th
