### ISSUE TITLE
issues meeting dec 29, 2017

### ISSUE THREAD

**Issue by pachamaltese** [datachile/datachile#326]
# Home
- [x] Write texts in english (i.e comunas instead of HOME.CAROUSEL.COMUNAS_POPULATION)
- [x] Clicking does not always change icons and colours
- [x] On products, use level II images (i.e fish for fish and not cow picture for fish)

# Footer
- [x] Group brand icons
- [x] Add links to sponsors

# About
- [x] Check Chilecube and fix the number of sources and datasets being used
- [x] Complete tax data information

# Geo Profile

## General
- [x] Use image of comunas (i.e do not use Costanera Center for everything on MR)
- [x] Fix clicks from browser (i.e it just works ok in geo profile)
- [ ] Fix D3plus callbacks (ask Dave)

## Splash
- [x] Fix parties names and show them in spanish
- [x] Fix fired congresspersonss (i.e Orpiz and Morerior)

## Economy
- [x] Add HS92 cube for product space
- [x] Check nodes without data in product space
- [x] Some render exceptions hang the site
- [x] Replace USSR, East Germany, etc accordingly
- [ ] Put products with exporting opportunity in datums (i.e products with RCA >= 1)
- [x] Complete employment texts
- [x] Complete opportunities texts
- [x] Complete employment texts
- [x] Express employment in %s and not #s
- [x] After writing employment in %s convert employment by level to a treemap
- [x] Replace mean income by median income (we are using medians)
- [x] Add note stating that R+D corresponds just to private companies expenditure
- [x] Do not bring all the data from the cube and filter later, instead just bring just the required data
- [x] Fix data loading from url (i.e from browser it loads much less data but from url it loads a lot of data)
- [x] Check hundreds vs thousands errors (i.e some treemaps say 42.08 billion imports while others say 420.8 billion imports)
- [x] Add text to trade balance

## Employment
- [ ] Show CI for $ of employed people
- [x] Use rounded numbers on datums (i.e 150,000 workers instead of 149,879)

## Education
- [x] Show just top schools at country level (Cesar said at region level we should display the top 10 on psu vs nem and on a list to the side the top 15 at country level)
- [x] Complete education texts
- [x] Check performance data
- [x] Check NEM vs dependency chart (i.e add note if this does not come from psu cube and included people not applying PSU instead)
- [x] Add enrollment texts
- [x] Add years corresponding to the data
- [x] Complete higher education charts (i.e we have placeholders at the moment)
- [x] Fix psu vs nem borders (i.e problems with mac scroll)

## Housing
- [x] Remove "and environment"
- [x] Texts in amenities
- [x] Years of data in amenities
- [x] Devices' datum
- [x] Replace internet access placeholder

## Demography
- [x] Add years of data
- [x] Complete texts
- [x] FIx population pyramid
- [x] Remove datums from text

# Country Profile
- [x] China does not load unless realoading the tab or going back

# Misc
- [x] Talk to Martner to now what "tax data" is where this comes from

**Comment by cnavarreteliz** [comment]
@palamago created a thread about `D3plus callbacks` in Slack
