### ISSUE TITLE
Geographic: Most exported (list top 5 products under visualization) — Product space — ECONOMÍA

### ISSUE THREAD

**Issue by jazzido** [datachile/datachile#35]
- Profile type: *Geographic*
- Topic: *ECONOMÍA*
- Section: *OPORTUNIDADES*
- Sub Section: *Product space*
- Title: *Most exported (list top 5 products under visualization)*
- Chart type: *Network diagram*
- Data source: **
- Official source: **
- Cube query: **

**Comment by cnavarreteliz** [comment]
After May 11th we will create news issues related with new visualizations
