### ISSUE TITLE
Geographic: Most complexity  (list top 5 products under visualization) — Product space — ECONOMÍA

### ISSUE THREAD

**Issue by jazzido** [datachile/datachile#36]
- Profile type: *Geographic*
- Topic: *ECONOMÍA*
- Section: *OPORTUNIDADES*
- Sub Section: *Product space*
- Title: *Most complexity  (list top 5 products under visualization)*
- Chart type: **
- Data source: **
- Official source: **
- Cube query: **

**Comment by cnavarreteliz** [comment]
We're not complexity index for every product in Datachile
