### ISSUE TITLE
Geographic: Most density  (list top 5 products under visualization) — Product space — ECONOMÍA

### ISSUE THREAD

**Issue by jazzido** [datachile/datachile#37]
- Profile type: *Geographic*
- Topic: *ECONOMÍA*
- Section: *OPORTUNIDADES*
- Sub Section: *Product space*
- Title: *Most density  (list top 5 products under visualization)*
- Chart type: **
- Data source: **
- Official source: **
- Cube query: **

**Comment by cnavarreteliz** [comment]
After May 11th we will create news issues related with new visualizations
