### ISSUE TITLE
Geographic: Top industries (list top 5 products under visualization) — Industry space — ECONOMÍA

### ISSUE THREAD

**Issue by jazzido** [datachile/datachile#38]
- Profile type: *Geographic*
- Topic: *ECONOMÍA*
- Section: *OPORTUNIDADES*
- Sub Section: *Industry space*
- Title: *Top industries (list top 5 products under visualization)*
- Chart type: *Community circles diagram*
- Data source: **
- Official source: **
- Cube query: **

**Comment by cnavarreteliz** [comment]
After May 11th we will create news issues related with new visualizations
