### ISSUE TITLE
Geographic: Top employment  (list top 5 products under visualization) — Industry space — ECONOMÍA

### ISSUE THREAD

**Issue by jazzido** [datachile/datachile#39]
- Profile type: *Geographic*
- Topic: *ECONOMÍA*
- Section: *OPORTUNIDADES*
- Sub Section: *Industry space*
- Title: *Top employment  (list top 5 products under visualization)*
- Chart type: **
- Data source: **
- Official source: **
- Cube query: **

**Comment by cnavarreteliz** [comment]
Occupations are not connected with products
