### ISSUE TITLE
Geographic: Most density industries  (list top 5 products under visualization) — Industry space — ECONOMÍA

### ISSUE THREAD

**Issue by jazzido** [datachile/datachile#40]
- Profile type: *Geographic*
- Topic: *ECONOMÍA*
- Section: *OPORTUNIDADES*
- Sub Section: *Industry space*
- Title: *Most density industries  (list top 5 products under visualization)*
- Chart type: **
- Data source: **
- Official source: **
- Cube query: **

**Comment by cnavarreteliz** [comment]
We're not density by industry in Datachile
