### ISSUE TITLE
0.0% datums are errors or no data?

### ISSUE THREAD

**Issue by gabrielaperezponce** [datachile/datachile#417]
industrias < actividades artísticas... < actividades artísticas... < I+D

https://es.datachile.io/industries/actividades-artisticas-de-entretenimiento-y-recreativas-R/actividades-creativas-artisticas-y-de-entretenimiento-90#opportunities

![numeros](https://user-images.githubusercontent.com/5561308/34946101-4a4e7e80-f9e4-11e7-9705-d0ce9bf38090.png)

**Comment by cnavarreteliz** [comment]
Checked, and there wasn't data for that industry.
