### ISSUE TITLE
Geographic: Dependencias de educación superior (universidades, cft, etc) — PSU — EDUCACIÓN

### ISSUE THREAD

**Issue by jazzido** [datachile/datachile#53]
- Profile type: *Geographic*
- Topic: *EDUCACIÓN*
- Section: *EDUCACIÓN SUPERIOR*
- Sub Section: *PSU*
- Title: *Dependencias de educación superior (universidades, cft, etc)*
- Chart type: *Treemap*
- Data source: **
- Official source: **
- Cube query: *http://chilecube.datawheel.us/ui/#eyJkcmlsbERvd25zIjpbWyJJbnN0aXR1dGlvbiBUeXBlIiwiSW5zdGl0dXRpb24gVHlwZSIsIkluc3RpdHV0aW9uIFR5cGUiXV0sImN1dHMiOltdLCJjdWJlIjoiZWR1Y2F0aW9uX2VtcGxveWFiaWxpdHkifQ==*

**Comment by cnavarreteliz** [comment]
The idea in the future is to create an "Institution Profile" with that data.
