### ISSUE TITLE
Geographic: Distribución de notas enseñanza media — Notas enseñanza media — EDUCACIÓN

### ISSUE THREAD

**Issue by jazzido** [datachile/datachile#54]
- Profile type: *Geographic*
- Topic: *EDUCACIÓN*
- Section: *NEM*
- Sub Section: *Notas enseñanza media*
- Title: *Distribución de notas enseñanza media*
- Chart type: *Bar chart*
- Data source: *http://pacha.datawheel.us/education/psu/csv/*
- Official source: **
- Cube query: *https://chilecube.datawheel.us/ui/#eyJkcmlsbERvd25zIjpbWyJEYXRlIiwiRGF0ZSIsIlllYXIiXV0sImN1dHMiOltbWzMxMCwzNjAsMzYxLDM2MiwzNjMsNDEwLDQ2MCw0NjEsNDYzLDUxMCw1NjAsNTYxLDU2Myw2MTAsNjYwLDY2MSw2NjMsNzEwLDc2MCw3NjEsNzYzLDgxMCw4NjAsODYzLDkxMCw5NjNdLFsiVGVhY2hpbmdzIiwiVGVhY2hpbmciLCJUZWFjaGluZyJdXV0sImN1YmUiOiJlZHVjYXRpb25fcGVyZm9ybWFuY2UiLCJtZWFzdXJlcyI6WyJBdmVyYWdlIFNjb3JlIEF2ZXJhZ2UgKD8pIl19*

**Comment by cnavarreteliz** [comment]
We made a similar Distribution chart with PSU and SNED data.
