### ISSUE TITLE
missing/incorrect English translations

### ISSUE THREAD

**Issue by davelandry** [datachile/datachile#540]
### About the Data
- [x] "Datos" ([subnav and page title](https://en.staging.datachile.io/about/data))
- [x] CASEN download links ([here](https://en.staging.datachile.io/about/data#dataset_casen))

### About the API
- [x] "Cubo" ([title](https://en.staging.datachile.io/about/api))
- [x] "For a~n~ particular cube, get the members belonging to a certain level in a dimension." (remove the "n" from "an"
- [x] Change "These data are gotten since" to "This data is provided by"

### Changelog
- [x] "ABOUT.CHANGELOG.FITZROYA.TITLE"
- [x] "about.changelog.fitzroya.description"

### Location Profile
- [x] "PROYECCIONES DE POBLACIÓN"
- [x] "NUEVA ENCUESTA SUPLEMENTARIA DE INGRESOS"
- [x] "PRUEBA DE SELECCIÓN UNIVERSITARIA"
- [x] "ESCUELAS TOTALES POR TIPO" (Education -> Enrollment)
- [x] All building materials (in Viz and Text) missing translations

### Industry Profile
- [x] "DATOS DE COSTES Y PRODUCCIÓN"

### Site-wide
- [x] change "Demography" to "Demographics"

**Comment by frabarz** [comment]
Are the string in Location/Industry Profile the sources under the charts? Should we translate these too?

The "NUEVA ENCUESTA SUPLEMENTARIA DE INGRESOS" is the name of the survey, and "PRUEBA DE SELECCIÓN UNIVERSITARIA" is the name of the exam, the other I think can be translated, but refer to the labels in their respective source sites.

**Comment by davelandry** [comment]
@frabarz ahhhh I see that makes sense. I saw those Location Profile labels underneath the top splash statistics and thought they were labels.

That being said, if possible, I think we should also translate the names of the source surveys.
