### ISSUE TITLE
design tweaks to profile maps

### ISSUE THREAD

**Issue by davelandry** [datachile/datachile#547]
Here's two small tweaks which would make the maps on the profile pages look much better. Currently looks like this:

![image 1](https://user-images.githubusercontent.com/1847581/39636324-ddadf59e-4f8d-11e8-8d7c-95c70c3927ed.png)

- [x] set `ocean: "#d6dadc"` so that it matches the color in the map tiles
- [ ] unless there's actually data for it... use `fitFilter` to hide Antarctica, it takes up so much space!

**Comment by cnavarreteliz** [comment]
```
fitFilter: d => {
    return ["ATA"].indexOf(d.id) < 0;
},
```

And looks like this:
![image](https://user-images.githubusercontent.com/5233593/39638134-9ce638b0-4f9b-11e8-8f10-f4259fcf5614.png)
