### ISSUE TITLE
profile map improvements

### ISSUE THREAD

**Issue by davelandry** [datachile/datachile#554]
Using [this](https://es.staging.datachile.io/products/productos-del-reino-vegetal-02/tomates-020702#trade) chart as an example:

<img width="612" alt="screen shot 2018-05-14 at 1 26 54 pm" src="https://user-images.githubusercontent.com/1847581/40013070-8b4917ee-577a-11e8-9c5e-32c8e7670149.png">

- [x] turn off map tiles (`tiles: false`)
- [x] change ocean to match page (`ocean: "#2f2f38"`)
- [x] remove extra empty padding underneath legend

**Comment by cnavarreteliz** [comment]
![image](https://user-images.githubusercontent.com/5233593/40021643-6bfefbb0-5793-11e8-8a77-99d78f49e489.png)
