### ISSUE TITLE
Splash images aren't displayed on continent profiles

### ISSUE THREAD

**Issue by perpetualgrimace** [datachile/datachile#566]
![no-country-image](https://user-images.githubusercontent.com/6193798/44289593-00849e80-a243-11e8-9409-d1fb5505c8f2.png)

**Comment by perpetualgrimace** [comment]
List of affected profiles:
- [datachile.io/countries/africa-2]
- [datachile.io/countries/oceania-9]
- [datachile.io/countries/americas-19]
- [datachile.io/countries/asia-142]
- [datachile.io/countries/europe-150]
- [datachile.io/countries/other-999]

Note: continents are also tagged as countries.

**Comment by gabrielaperezponce** [comment]
Country Profiles that do not have splash images:

**AFRICA**
Bostwana
Lesotho
Comoras
Swazilandia
Cabo verde
Mali
Somalia
Burundi
Rwanda
Congo (EX ZAIRE), República democrática del
Congo Republica del **(modify title order in Spanish)**
Santo Tome y Principe
Bophuthatswana
Djibouti
Namibia
Eritrea

**OCEANIA**
Islas Marshall
Fiji
Nauru
Tonga (Isla Tonga)
Vanuatu
Kiribati
Tuvalu
Palau (EX BELAU)
Niue
Nueva Caledonia
Islas Marianas del Norte
Guam
Islas Cook

**AMERICA**
**Barbados**  It has the same photo as **Benin** in **Africa**
Granada
San Vicente y las Granadinas
Suriname
Belice
Antigua y Barbuda
Saint Kitts & Nevis
Anguila
Aruba
Bermudas
Turcas y Caicos
Islas Virgenes (Estados Unidos de America)
Martinica
Montserrat
Groenlandia

**ASIA**
**Oman** has a picture of **sacks with seeds**
Afghanistan
Bhutan
**Nepal** It has the same photo as **Guatemala**
Yemen de Norte  **(should say “del”)**
Yemen del Sur
Maldivas (Isla Maldivas)
Timor Oriental
Tadjikistan

**EUROPA**
República Federal Alemana (RFA)
República Democrática Alemana (RDA)
Irlanda
Federación Rusa
Ciudad de Vaticano
Andorra
Yugoslavia
Luxemburgo
Liechtenstein
Monaco
San Marino
Montenegro
Gibraltar
Isla de Man
Jersey

**OTROS**
All links go to a “Page not found”

<img width="1422" alt="captura de pantalla 2018-08-20 a la s 12 05 16" src="https://user-images.githubusercontent.com/5561308/44348647-60608c80-a471-11e8-8a18-16c3fcf2ede6.png">

**Comment by palamago** [comment]
Consider that: for Africa for example: The image is here: https://es.datachile.io/images/profile-bg/country/continent/2.jpg but the request in profile page is to: https://es.datachile.io/images/profile-bg/country/2.jpg
