### ISSUE TITLE
missing x axis labels in Migration by Sex bar

### ISSUE THREAD

**Issue by perpetualgrimace** [datachile/datachile#586]
Labels refuse to appear, and won't rotate. Applies to Migration by Sex in both geo & country profiles.

**NOTE**: as of 10-15, this is only a stacked bar over time in the `design` branch

![where-my-labels-at](https://user-images.githubusercontent.com/6193798/46979238-1b3a8e80-d09f-11e8-8aca-e78ba88704e7.gif)

@davelandry requested that I try to recreate the issue, so I did so — but I'm not seeing it there. Check it out:
https://codepen.io/perpetualgrimace/pen/yRPxpw?editors=0010

**Comment by cnavarreteliz** [comment]
closed via [e724bdd](https://github.com/datachile/datachile/commit/e724bdd176bf27826604904a8e82dd26c54b431f)

**Comment by davelandry** [comment]
@cnavarreteliz it's hard to see from your commit what has changed, what was the fix for this?

**Comment by cnavarreteliz** [comment]
@davelandry 😄 I used spaces instead of tabs. 
The previous config of x-axis was:
```
xConfig: {
    tickFormat: d => " ",
    title: false
}
```

I deleted `tickFormat: d => " "` and I fixed this issue :)

**Comment by perpetualgrimace** [comment]
That didn't seem to do the trick, unfortunately.

<img width="506" alt="nope" src="https://user-images.githubusercontent.com/6193798/47032660-e5e67d00-d140-11e8-8e21-4eab546f254a.png">

**Comment by perpetualgrimace** [comment]
Here's another case of the same issue in geo/demographics/population

<img width="396" alt="also-nope" src="https://user-images.githubusercontent.com/6193798/47034155-8d18e380-d144-11e8-92c1-d23af8321995.png">
