### ISSUE TITLE
Totals above visualizations display incorrect value

### ISSUE THREAD

**Issue by perpetualgrimace** [datachile/datachile#600]
From Cesar's ppt:
![clearly-wrong](https://user-images.githubusercontent.com/6193798/47045235-551f9980-d160-11e8-9e37-1088edbde61c.png)
![wrong-number](https://user-images.githubusercontent.com/6193798/47045236-551f9980-d160-11e8-884c-52199d01d3b7.png)
![wrong-number-again](https://user-images.githubusercontent.com/6193798/47045237-551f9980-d160-11e8-935f-7f3fc3992650.png)

**Comment by cnavarreteliz** [comment]
closed via #604
