### ISSUE TITLE
explore — child profiles without images should inherit parent profile image

### ISSUE THREAD

**Issue by perpetualgrimace** [datachile/datachile#602]
Doable?

![tiles-no-backup-images](https://user-images.githubusercontent.com/6193798/47046049-3f12d880-d162-11e8-8ee3-d43984d371eb.png)

**Comment by palamago** [comment]
We changed the url every time and this is good for SEO, we have to dig a little bit and see if we can prevent this but I do not think so.
A weird thing is the "0 of 1 dataset" message.
